0_APP:
    PATH_TO_ENERGYPLUS: C:/EnergyPlusV9-1-0                                      #[Str] this is for energyplus.exe path
    PATH_TO_RESULTS: ../../MUBES_SimResults/                                     #[Str] this is the main folder where the results will be stored. it will be created if not exists
1_DATA:
    PATH_TO_DATA : ../ModelerFolder/Minneberg_Buildings_v1.geojson               #[Str] Input file or folder in case of several files
2_CASE:
    0_GrlChoices :
        CaseName : 'ForTest'                    #[Str] Name of the studied Case, a subfolder of this name will be created in the main folder defined in '0_APP:PATH_TO_RESULTS'
        OutputsFile : 'Outputs_Template.txt'    #[Str] Output file to identify the outputs the modeller would want and their frequency
        RefreshFolder : True                    #[Bool] True : the folder CaseName, if exist, is emptied whatever could be in it
        MakePlotsOnly : False                   #[Bool] True : a figure will be created with the buildings specified in UUID
        MakePlotsPerBld : False                 #[Bool] True : a figure is created for each building including it's shadowing surfaces (if present)
        Verbose : True                          #[Bool] True : Gives messages in the prompt window along the ongoing process
        CPUusage : 0.8                          #[Float] Factor of CPU allowed to be used during parallel computing
        DebugMode : False                       #[Bool] The log file will be feeded by detailed information along the process
3_SIM :
    #files are needed to be located in the eather folder of EnergyPlus asthe same path is used afterward to launch the simulation
    1_WeatherFile :
        Loc : 'WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw' #[Str] Need to be a epw file. This one is given because installed by default when installing EnergyPlus
